version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: savenserve-db
    environment:
      MYSQL_ROOT_PASSWORD: Madeena@2025
      MYSQL_DATABASE: sdpproject
      MYSQL_USER: Madeena
      MYSQL_PASSWORD: Madeena@2025
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build:
      context: ./SPRINGBOOTWORKSPACE/SDPProject
    container_name: savenserve-backend
    ports:
      - "2004:2004"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/sdpproject
      SPRING_DATASOURCE_USERNAME: Madeena
      SPRING_DATASOURCE_PASSWORD: 

  frontend:
    build:
      context: ./REACTJS/frontend
    container_name: savenserve-frontend
    ports:
      - "8081:80"
    depends_on:
      - backend

volumes:
  mysql-data:
